/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as ServersServerIdRouteImport } from './routes/servers.$serverId'
import { Route as MeConversationsConversationIdRouteImport } from './routes/me.conversations.$conversationId'
import { Route as ServersServerIdIndexRouteImport } from './routes/servers.$serverId.index'
import { Route as ServersServerIdChannelsChannelIdRouteImport } from './routes/servers.$serverId.channels.$channelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeConversationsConversationIdRoute =
  MeConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => MeRoute,
  } as any)
const ServersServerIdIndexRoute = ServersServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServersServerIdRoute,
} as any)
const ServersServerIdChannelsChannelIdRoute =
  ServersServerIdChannelsChannelIdRouteImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => ServersServerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/me/': typeof MeIndexRoute
  '/me/conversations/$conversationId': typeof MeConversationsConversationIdRoute
  '/servers/$serverId/': typeof ServersServerIdIndexRoute
  '/servers/$serverId/channels/$channelId': typeof ServersServerIdChannelsChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeIndexRoute
  '/me/conversations/$conversationId': typeof MeConversationsConversationIdRoute
  '/servers/$serverId': typeof ServersServerIdIndexRoute
  '/servers/$serverId/channels/$channelId': typeof ServersServerIdChannelsChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/me/': typeof MeIndexRoute
  '/me/conversations/$conversationId': typeof MeConversationsConversationIdRoute
  '/servers/$serverId/': typeof ServersServerIdIndexRoute
  '/servers/$serverId/channels/$channelId': typeof ServersServerIdChannelsChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/me'
    | '/servers/$serverId'
    | '/me/'
    | '/me/conversations/$conversationId'
    | '/servers/$serverId/'
    | '/servers/$serverId/channels/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/me'
    | '/me/conversations/$conversationId'
    | '/servers/$serverId'
    | '/servers/$serverId/channels/$channelId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/me'
    | '/servers/$serverId'
    | '/me/'
    | '/me/conversations/$conversationId'
    | '/servers/$serverId/'
    | '/servers/$serverId/channels/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRouteWithChildren
  ServersServerIdRoute: typeof ServersServerIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/conversations/$conversationId': {
      id: '/me/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/me/conversations/$conversationId'
      preLoaderRoute: typeof MeConversationsConversationIdRouteImport
      parentRoute: typeof MeRoute
    }
    '/servers/$serverId/': {
      id: '/servers/$serverId/'
      path: '/'
      fullPath: '/servers/$serverId/'
      preLoaderRoute: typeof ServersServerIdIndexRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/servers/$serverId/channels/$channelId': {
      id: '/servers/$serverId/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/servers/$serverId/channels/$channelId'
      preLoaderRoute: typeof ServersServerIdChannelsChannelIdRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
  }
}

interface MeRouteChildren {
  MeIndexRoute: typeof MeIndexRoute
  MeConversationsConversationIdRoute: typeof MeConversationsConversationIdRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeIndexRoute: MeIndexRoute,
  MeConversationsConversationIdRoute: MeConversationsConversationIdRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

interface ServersServerIdRouteChildren {
  ServersServerIdIndexRoute: typeof ServersServerIdIndexRoute
  ServersServerIdChannelsChannelIdRoute: typeof ServersServerIdChannelsChannelIdRoute
}

const ServersServerIdRouteChildren: ServersServerIdRouteChildren = {
  ServersServerIdIndexRoute: ServersServerIdIndexRoute,
  ServersServerIdChannelsChannelIdRoute: ServersServerIdChannelsChannelIdRoute,
}

const ServersServerIdRouteWithChildren = ServersServerIdRoute._addFileChildren(
  ServersServerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRouteWithChildren,
  ServersServerIdRoute: ServersServerIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
